# Generated by Django 3.2 on 2022-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('style', models.CharField(choices=[('photography', 'photography'), ('sculpture', 'sculpture'), ('painting', 'painting'), ('video', 'video')], default=1, max_length=254)),
                ('description', models.TextField()),
                ('photographer_artist', models.CharField(blank=True, max_length=254)),
                ('entrance_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gallery_area', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=254)),
                ('now_showing', models.BooleanField(default=False)),
                ('date_starting', models.DateField()),
                ('date_finishing', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
