# Generated by Django 3.2 on 2022-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.CharField(choices=[('photography', 'photography'), ('sculpture', 'sculpture'), ('painting', 'painting'), ('video', 'video')], default=1, max_length=15)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('photographer_artist', models.CharField(max_length=50)),
                ('entrance_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gallery_area', models.CharField(choices=[('main gallery', 'main gallery'), ('studio', 'studio'), ('basement', 'basement')], default='main gallery', max_length=254)),
                ('display', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('finished', 'finished'), ('now showing', 'now showing'), ('coming soon', 'coming soon'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='now showing', max_length=254)),
                ('date_starting', models.DateField(blank=True, null=True)),
                ('date_finishing', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Exhibitions',
            },
        ),
    ]
