# Generated by Django 3.2 on 2022-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitions',
            options={'verbose_name_plural': 'Exhibitions'},
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='status',
            field=models.CharField(choices=[('past', 'past'), ('now showing', 'now showing'), ('coming soon', 'coming soon')], default=1, max_length=254),
        ),
    ]
