# Generated by Django 3.2 on 2022-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20220406_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='date_finishing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='date_starting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='gallery_area',
            field=models.CharField(choices=[('main gallery', 'main gallery'), ('studio', 'studio'), ('basement', 'basement')], default='main gallery', max_length=254),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='status',
            field=models.CharField(choices=[('past', 'past'), ('now showing', 'now showing'), ('coming soon', 'coming soon'), ('pending', 'pending')], default='now showing', max_length=254),
        ),
    ]
