# Generated by Django 3.2 on 2022-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20220407_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='status',
            field=models.CharField(choices=[('past', 'past'), ('now showing', 'now showing'), ('coming soon', 'coming soon'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='now showing', max_length=254),
        ),
    ]
