# Generated by Django 3.2 on 2022-04-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_rename_now_showing_exhibitions_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='status',
            field=models.CharField(choices=[('finished', 'finished'), ('now showing', 'now showing'), ('coming soon', 'coming soon'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='now showing', max_length=254),
        ),
    ]
