# Generated by Django 3.2 on 2022-03-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220322_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_sucess',
            new_name='order_success',
        ),
    ]
