# Generated by Django 3.2 on 2022-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_order_sucess_order_order_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('GB', 'United Kingdom')], default='United Kingdom', max_length=20),
        ),
    ]
