# Generated by Django 3.2 on 2022-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_quantity_in_stock'),
        ('checkout', '0006_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=models.SET('product deleted.'), to='products.product'),
        ),
    ]
