# Generated by Django 3.2 on 2022-04-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_success',
        ),
    ]
