# Generated by Django 3.2 on 2022-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateField(auto_now=True),
        ),
    ]
