# Generated by Django 3.2 on 2022-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
