# Generated by Django 3.2 on 2022-03-10 10:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220308_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=products.models.MediaFileSystemStorage(), upload_to=''),
        ),
    ]
