# Generated by Django 3.2 on 2022-04-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_quantity_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='style',
            new_name='category',
        ),
    ]
